"""
Aggregation data models per v1.3 spec §2.

These dataclasses define the core structures for aggregation queries:
- AggIntent: Parsed user intent (§2.1)
- CAT: Canonical Aggregation Target (§2.2)
- ResultKind: User-truthfulness contract (§2.3)
- EvidenceEnvelope: Audit trail without payload bloat (§2.4)
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union
from uuid import UUID


class IntentKind(str, Enum):
    """Aggregation intent taxonomy (§3.1-3.10)."""
    COUNT = "COUNT"
    COUNT_DISTINCT = "COUNT_DISTINCT"
    SUM = "SUM"
    AVG = "AVG"
    MIN = "MIN"
    MAX = "MAX"
    GROUP_BY = "GROUP_BY"
    TREND = "TREND"
    TOP_K = "TOP_K"
    GRAPH_COUNT = "GRAPH_COUNT"
    PROVENANCE_COUNT = "PROVENANCE_COUNT"


class ResultKind(str, Enum):
    """Result kinds per §2.3 user-truthfulness contract."""
    EXACT = "EXACT"           # Closed-world + deterministic; point value safe
    LOWER_BOUND = "LOWER_BOUND"  # Open-world or incomplete; "at least N"
    RANGE = "RANGE"           # Conflicts or multi-source; "between N and M"
    INSUFFICIENT = "INSUFFICIENT"  # Cannot compute safe bounds


class ClosurePolicy(str, Enum):
    """Data completeness declaration."""
    AUTHORITATIVE = "AUTHORITATIVE"  # Closed-world; EXACT possible
    PARTIAL = "PARTIAL"              # Known gaps; LOWER_BOUND likely
    OPEN_WORLD = "OPEN_WORLD"        # Unknown completeness; LOWER_BOUND required


class DedupPolicy(str, Enum):
    """Deduplication strategy."""
    CANONICAL_ID = "CANONICAL_ID"      # Use resolved entity IDs
    FUZZY_HINTS = "FUZZY_HINTS"        # Use similarity scores
    TEMPORAL_MERGE = "TEMPORAL_MERGE"  # Merge overlapping time ranges
    EXACT = "EXACT"                    # No dedup; trust source


class TimeMode(str, Enum):
    """Time semantics for aggregation."""
    EVENT_TIME = "event_time"    # When event occurred
    VALID_TIME = "valid_time"    # When fact was valid
    SYS_TIME = "sys_time"        # When recorded in system
    UNSPECIFIED = "unspecified"


class TargetSource(str, Enum):
    """Source of data to aggregate."""
    KG_RELATIONSHIP = "KG_RELATIONSHIP"
    ENTITY_TABLE = "ENTITY_TABLE"
    DTL_DECISION = "DTL_DECISION"
    DOCUMENT_MENTION = "DOCUMENT_MENTION"


@dataclass
class AnchorEntity:
    """Resolved entity that anchors the aggregation."""
    entity_id: UUID
    entity_type: str
    name: Optional[str] = None


@dataclass
class Filter:
    """Query filter predicate."""
    path: str           # e.g., "attributes.status"
    op: str             # e.g., "!=", "IN", "BETWEEN"
    value: Any          # e.g., "deleted", ["active", "pending"]
    required: bool = True
    raw: Optional[str] = None  # Original user text


@dataclass
class TimeWindow:
    """Time bounds for aggregation."""
    start: Optional[datetime] = None
    end: Optional[datetime] = None
    mode: TimeMode = TimeMode.UNSPECIFIED
    field: Optional[str] = None  # e.g., "valid_from"
    inferred: bool = False  # True if system guessed window


@dataclass
class GraphConfig:
    """Graph traversal configuration."""
    direction: str = "outgoing"  # "incoming" | "outgoing"
    max_hops: int = 1
    dedup_nodes: bool = True
    relationship_types: List[str] = field(default_factory=list)


@dataclass
class AggIntent:
    """
    Parsed aggregation intent from user query (§2.1).
    
    Created by intent classifier, consumed by semantic resolver.
    """
    kind: IntentKind
    subject_phrase: str  # "jobs", "incidents", "approvals"
    anchor_entities: List[AnchorEntity] = field(default_factory=list)
    filters: List[Filter] = field(default_factory=list)
    group_by: List[str] = field(default_factory=list)
    top_k: Optional[Dict[str, Any]] = None  # {"k": 5, "direction": "desc"}
    time_window: Optional[TimeWindow] = None
    raw_query: Optional[str] = None


@dataclass
class AggregationSpec:
    """Aggregation operation specification."""
    op: IntentKind
    value_expr: Optional[str] = None  # For SUM/AVG: column to aggregate
    grouping_key: List[str] = field(default_factory=list)


@dataclass
class TargetSpec:
    """What to aggregate over."""
    source: TargetSource
    entity_type: Optional[str] = None
    relationship_type: Optional[str] = None


@dataclass
class CAT:
    """
    Canonical Aggregation Target (§2.2).
    
    The semantic contract that defines "what exactly are we counting?"
    Generated by semantic resolver, consumed by planner.
    """
    tenant_id: UUID
    anchor: Optional[AnchorEntity]
    target: TargetSpec
    aggregation: AggregationSpec
    
    # Filters and time
    filters: List[Filter] = field(default_factory=list)
    time: Optional[TimeWindow] = None
    
    # Graph config (for GRAPH_COUNT)
    graph: Optional[GraphConfig] = None
    
    # Policies
    closure_policy: ClosurePolicy = ClosurePolicy.PARTIAL
    dedup_policy: DedupPolicy = DedupPolicy.CANONICAL_ID
    
    # Confidence and assumptions
    semantic_confidence: float = 0.0
    assumptions: List[str] = field(default_factory=list)
    
    # Alternatives (for disambiguation)
    alternatives: List["CAT"] = field(default_factory=list)
    alternative_reason: Optional[str] = None


@dataclass
class EvidenceEnvelope:
    """
    Audit trail for aggregation results (§2.4).
    
    Stores enough for reproducibility without payload bloat.
    """
    plan_hash: str                    # SHA256 of execution plan
    sql: str                          # Executed SQL (or reference)
    params: Dict[str, Any]            # Query parameters
    snapshot_time: datetime           # When executed
    rowset_handle: Optional[str] = None  # For drill-down pagination
    sample_ids: List[str] = field(default_factory=list)  # Sample for citations
    source_ids: List[str] = field(default_factory=list)  # Provenance sources


@dataclass
class BoundedCount:
    """Result of Lincoln-Petersen estimation or bounded counting."""
    lower: int
    upper: Optional[int] = None
    expected: Optional[int] = None
    method: str = "exact"  # "exact", "lincoln_petersen", "union_only"


@dataclass
class ConfidenceComponents:
    """Breakdown of confidence score."""
    semantic_clarity: float = 1.0
    closure_factor: float = 1.0
    coverage: float = 1.0
    conflict_penalty: float = 0.0
    entity_resolution_penalty: float = 0.0


@dataclass
class SufficiencyDecision:
    """Output of the sufficiency gate (§5)."""
    result_kind: ResultKind
    confidence: float
    confidence_components: ConfidenceComponents
    bounds: Optional[BoundedCount] = None
    reasons: List[Dict[str, str]] = field(default_factory=list)
    assumptions: List[str] = field(default_factory=list)
    next_best_actions: List[str] = field(default_factory=list)


@dataclass
class AggregationResult:
    """
    Complete result of an aggregation query.
    
    Returned by AggregationService.handle_query().
    """
    # Primary result
    result_kind: ResultKind
    value: Optional[Union[int, float]] = None
    bounds: Optional[BoundedCount] = None
    unit: Optional[str] = None
    
    # Confidence
    confidence: float = 0.0
    confidence_label: str = "Unknown"
    confidence_components: Optional[ConfidenceComponents] = None
    
    # Semantic clarity
    definition: Optional[Dict[str, Any]] = None
    assumptions: List[str] = field(default_factory=list)
    
    # Evidence
    evidence_envelope: Optional[EvidenceEnvelope] = None
    citations: List[Dict[str, Any]] = field(default_factory=list)
    
    # Alternatives
    alternatives: List[Dict[str, Any]] = field(default_factory=list)
    
    # For ContextBundle integration
    cat: Optional[CAT] = None
    raw_query: Optional[str] = None
    
    # The actual entities that were counted - for rich responses and follow-ups
    counted_entities: List[Dict[str, Any]] = field(default_factory=list)
    
    @property
    def display_text(self) -> str:
        """Human-readable result string."""
        if self.result_kind == ResultKind.EXACT:
            return f"{self.value} {self.unit or ''}"
        elif self.result_kind == ResultKind.LOWER_BOUND:
            return f"At least {self.bounds.lower if self.bounds else self.value} {self.unit or ''}"
        elif self.result_kind == ResultKind.RANGE:
            if self.bounds:
                return f"Between {self.bounds.lower} and {self.bounds.upper} {self.unit or ''}"
            return f"Unknown range"
        else:
            return "Insufficient data to count"
    
    @property
    def is_success(self) -> bool:
        """Whether we produced a usable count."""
        return self.result_kind != ResultKind.INSUFFICIENT
