"""
Extraction Interface Types
Platform Foundation → Queue → Brain → ExtractionResult

RFC v2 Interface Contract - Extraction Flow
"""

from datetime import datetime
from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field
from uuid import UUID


class ExtractionErrorCode(str, Enum):
    """Error codes for extraction operations."""
    EXTRACTION_SUCCESS = "EXTRACTION_SUCCESS"
    EXTRACTION_PARTIAL = "EXTRACTION_PARTIAL"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    EXTRACTION_TIMEOUT = "EXTRACTION_TIMEOUT"
    TOKEN_LIMIT_EXCEEDED = "TOKEN_LIMIT_EXCEEDED"
    MODEL_ERROR = "MODEL_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ExtractionMode(str, Enum):
    """Extraction mode options."""
    FULL = "full"
    INCREMENTAL = "incremental"


class Priority(str, Enum):
    """Priority levels for queue processing."""
    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"


class TokensConsumed(BaseModel):
    """Token consumption tracking for metering."""
    input_tokens: int = Field(ge=0, description="Tokens sent to LLM")
    output_tokens: int = Field(ge=0, description="Tokens received from LLM")
    total_tokens: int = Field(ge=0, description="Sum of input and output tokens")
    
    @classmethod
    def from_total(cls, total: int, input_ratio: float = 0.6) -> "TokensConsumed":
        """Create from total count with estimated split."""
        input_tokens = int(total * input_ratio)
        output_tokens = total - input_tokens
        return cls(
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=total
        )


class ExtractionError(BaseModel):
    """Error details for failed or partial extractions."""
    code: ExtractionErrorCode
    message: str = Field(description="Human-readable error message")
    recoverable: bool = Field(
        default=False,
        description="Whether Platform can retry the extraction"
    )


class ExtractionRequest(BaseModel):
    """
    Request submitted by Platform Foundation to extraction queue.
    
    Platform → Queue → Brain
    """
    request_id: str = Field(description="UUID, generated by Platform")
    document_id: str = Field(description="UUID, Platform's document record")
    tenant_id: str = Field(description="UUID, from authenticated session/API key")
    
    file_path: str = Field(
        description="Storage path: /tenants/{tenant_id}/documents/{doc_id}/v{n}/original.pdf"
    )
    file_name: str = Field(description="Original filename for context")
    mime_type: str = Field(
        description="e.g., application/pdf, application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    file_size_bytes: int = Field(ge=0, description="For estimation")
    
    ontology_hints: Optional[List[str]] = Field(
        default=None,
        description="e.g., ['fibo:financial', 'fhir:clinical'] - suggests which ontologies to prioritize"
    )
    extraction_mode: ExtractionMode = Field(
        default=ExtractionMode.FULL,
        description="Full or incremental extraction"
    )
    
    submitted_at: str = Field(description="ISO 8601 timestamp")
    priority: Priority = Field(default=Priority.NORMAL)
    
    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "123e4567-e89b-12d3-a456-426614174000",
                "document_id": "123e4567-e89b-12d3-a456-426614174001",
                "tenant_id": "123e4567-e89b-12d3-a456-426614174002",
                "file_path": "/tenants/xxx/documents/yyy/v1/original.pdf",
                "file_name": "contract.pdf",
                "mime_type": "application/pdf",
                "file_size_bytes": 1024000,
                "submitted_at": "2025-12-07T10:00:00Z"
            }
        }


class ExtractionResult(BaseModel):
    """
    Result written by Brain after extraction completes.
    
    Brain → Results Queue/Table → Platform
    """
    request_id: str = Field(description="Echo back from request")
    document_id: str = Field(description="Echo back from request")
    tenant_id: str = Field(description="Echo back from request")
    
    status: str = Field(
        description="success | partial | failed"
    )
    
    entities_extracted: int = Field(
        ge=0,
        default=0,
        description="Count of entities created"
    )
    relationships_extracted: int = Field(
        ge=0,
        default=0,
        description="Count of relationships created"
    )
    
    tokens_consumed: TokensConsumed = Field(
        description="Token usage for metering - CRITICAL for billing"
    )
    
    started_at: str = Field(description="ISO 8601 timestamp")
    completed_at: str = Field(description="ISO 8601 timestamp")
    duration_ms: int = Field(ge=0, description="Processing duration in milliseconds")
    
    error: Optional[ExtractionError] = Field(
        default=None,
        description="Error details if status is 'failed' or 'partial'"
    )
    
    extraction_version: str = Field(
        default="1.0.0",
        description="Version of extraction pipeline used"
    )
    model_used: str = Field(
        default="gpt-4o-mini",
        description="LLM model used for extraction"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "123e4567-e89b-12d3-a456-426614174000",
                "document_id": "123e4567-e89b-12d3-a456-426614174001",
                "tenant_id": "123e4567-e89b-12d3-a456-426614174002",
                "status": "success",
                "entities_extracted": 15,
                "relationships_extracted": 8,
                "tokens_consumed": {
                    "input_tokens": 3000,
                    "output_tokens": 2000,
                    "total_tokens": 5000
                },
                "started_at": "2025-12-07T10:00:00Z",
                "completed_at": "2025-12-07T10:00:30Z",
                "duration_ms": 30000,
                "extraction_version": "1.0.0",
                "model_used": "gpt-4o-mini"
            }
        }
